package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Abono generated by hbm2java
 */
@Entity
@Table(name="abono"
    ,catalog="jpro"
)
public class Abono  implements java.io.Serializable {


     private int idAbono;
     private String nombre;
     private String descripcion;
     private String aplicacion;
   
     @Id 

    
    @Column(name="id_abono", unique=true, nullable=false)
    public int getIdAbono() {
        return this.idAbono;
    }
    
    public void setIdAbono(int idAbono) {
        this.idAbono = idAbono;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="aplicacion", length=45)
    public String getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(String aplicacion) {
        this.aplicacion = aplicacion;
    }




}


