package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="jpro"
)
public class Area  implements java.io.Serializable {


     private int idArea;
     private String nombre;
     private String descripcionArea;
     private String areaEnMetros;
   
     @Id 

    
    @Column(name="id_area", unique=true, nullable=false)
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion_area", length=200)
    public String getDescripcionArea() {
        return this.descripcionArea;
    }
    
    public void setDescripcionArea(String descripcionArea) {
        this.descripcionArea = descripcionArea;
    }

    
    @Column(name="area_en_metros", length=100)
    public String getAreaEnMetros() {
        return this.areaEnMetros;
    }
    
    public void setAreaEnMetros(String areaEnMetros) {
        this.areaEnMetros = areaEnMetros;
    }




}


