package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.google.common.base.MoreObjects;

/**
 * Bajas generated by hbm2java
 */
@Entity
@Table(name="bajas"
    ,catalog="jpro"
)
public class Bajas  implements java.io.Serializable {


     private int idBajas;
     private Cultivo cultivo;
     private String cantidad;
     private String fechaRegistro;
     private String fechaBaja;
   
     @Id 

    
    @Column(name="id_bajas", unique=true, nullable=false)
    public int getIdBajas() {
        return this.idBajas;
    }
    
    public void setIdBajas(int idBajas) {
        this.idBajas = idBajas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cultivo_id_cultivo", nullable=false)
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="fecha_registro", length=45)
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="fecha_baja", length=45)
    public String getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(String fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("idBajas", idBajas)
				.add("cantidad", cantidad).add("fechaRegistro", fechaRegistro).add("fechaBaja", fechaBaja).toString();
	}


    

}


