package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.google.common.base.MoreObjects;

/**
 * Cultivo generated by hbm2java
 */
@Entity
@Table(name="cultivo"
    ,catalog="jpro"
)
public class Cultivo  implements java.io.Serializable {


     private int idCultivo;
     private Area area;
     private TipoDeCultivo tipoDeCultivo;
     private Integer cantidadPlanta;
     private Date fechaInicioProduccion;
     private Date fechaFinProduccion;
   
     @Id 

    
    @Column(name="id_cultivo", unique=true, nullable=false)
    public int getIdCultivo() {
        return this.idCultivo;
    }
    
    public void setIdCultivo(int idCultivo) {
        this.idCultivo = idCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_id_area", nullable=false)
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_de _cultivo_id_tipo_de_cultivo", nullable=false)
    public TipoDeCultivo getTipoDeCultivo() {
        return this.tipoDeCultivo;
    }
    
    public void setTipoDeCultivo(TipoDeCultivo tipoDeCultivo) {
        this.tipoDeCultivo = tipoDeCultivo;
    }

    
    @Column(name="cantidad_planta")
    public Integer getCantidadPlanta() {
        return this.cantidadPlanta;
    }
    
    public void setCantidadPlanta(Integer cantidadPlanta) {
        this.cantidadPlanta = cantidadPlanta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_inicio_produccion", length=19)
    public Date getFechaInicioProduccion() {
        return this.fechaInicioProduccion;
    }
    
    public void setFechaInicioProduccion(Date fechaInicioProduccion) {
        this.fechaInicioProduccion = fechaInicioProduccion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_fin_produccion", length=19)
    public Date getFechaFinProduccion() {
        return this.fechaFinProduccion;
    }
    
    public void setFechaFinProduccion(Date fechaFinProduccion) {
        this.fechaFinProduccion = fechaFinProduccion;
    }

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("idCultivo", idCultivo)
				.add("cantidadPlanta", cantidadPlanta)
				.add("fechaInicioProduccion", fechaInicioProduccion).add("fechaFinProduccion", fechaFinProduccion)
				.toString();
	}

    


}


