package com.jorge.springmvc.model;
// Generated 21/07/2017 05:30:53 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HarvestId generated by hbm2java
 */
@Embeddable
public class HarvestId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idHarvest;
	private int idUsuario;

	public HarvestId() {
	}

	public HarvestId(int idHarvest, int idUsuario) {
		this.idHarvest = idHarvest;
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_HARVEST", nullable = false)
	public int getIdHarvest() {
		return this.idHarvest;
	}

	public void setIdHarvest(int idHarvest) {
		this.idHarvest = idHarvest;
	}

	@Column(name = "ID_USUARIO", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HarvestId))
			return false;
		HarvestId castOther = (HarvestId) other;

		return (this.getIdHarvest() == castOther.getIdHarvest()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHarvest();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
