package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialQuimico generated by hbm2java
 */
@Entity
@Table(name="historial_quimico"
    ,catalog="jpro"
)
public class HistorialQuimico  implements java.io.Serializable {


     private int idHistorialQuimico;
     private Cultivo cultivo;
     private Quimico quimico;
     private String descripcion;
     private String cantidad;
     private Date fechaAplicacion;
   
     @Id 

    
    @Column(name="id_historial_quimico", unique=true, nullable=false)
    public int getIdHistorialQuimico() {
        return this.idHistorialQuimico;
    }
    
    public void setIdHistorialQuimico(int idHistorialQuimico) {
        this.idHistorialQuimico = idHistorialQuimico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cultivo_id_cultivo", nullable=false)
    public Cultivo getCultivo() {
        return this.cultivo;
    }
    
    public void setCultivo(Cultivo cultivo) {
        this.cultivo = cultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quimico_id_quimicos", nullable=false)
    public Quimico getQuimico() {
        return this.quimico;
    }
    
    public void setQuimico(Quimico quimico) {
        this.quimico = quimico;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_aplicacion", length=19)
    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }
    
    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }




}


