package com.jorge.springmvc.model;
// Generated 21/07/2017 05:30:53 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "jito_db")
public class Log implements java.io.Serializable {

	private LogId id;
	private User user;
	private String description;
	private String date;

	public Log() {
	}

	public Log(LogId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Log(LogId id, User user, String description, String date) {
		this.id = id;
		this.user = user;
		this.description = description;
		this.date = date;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idLog", column = @Column(name = "ID_LOG", nullable = false)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "ID_USUARIO", nullable = false)) })
	public LogId getId() {
		return this.id;
	}

	public void setId(LogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USUARIO", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DATE", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
