package com.jorge.springmvc.model;
// Generated 21/07/2017 05:30:53 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogId generated by hbm2java
 */
@Embeddable
public class LogId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idLog;
	private int idUsuario;

	public LogId() {
	}

	public LogId(int idLog, int idUsuario) {
		this.idLog = idLog;
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_LOG", nullable = false)
	public int getIdLog() {
		return this.idLog;
	}

	public void setIdLog(int idLog) {
		this.idLog = idLog;
	}

	@Column(name = "ID_USUARIO", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogId))
			return false;
		LogId castOther = (LogId) other;

		return (this.getIdLog() == castOther.getIdLog()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdLog();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
