package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quimico generated by hbm2java
 */
@Entity
@Table(name="quimico"
    ,catalog="jpro"
)
public class Quimico  implements java.io.Serializable {


     private int idQuimicos;
     private String nombre;
     private String descripcion;
     private String aplicacion;
   
     @Id 

    
    @Column(name="id_quimicos", unique=true, nullable=false)
    public int getIdQuimicos() {
        return this.idQuimicos;
    }
    
    public void setIdQuimicos(int idQuimicos) {
        this.idQuimicos = idQuimicos;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="aplicacion", length=45)
    public String getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(String aplicacion) {
        this.aplicacion = aplicacion;
    }




}


