package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import com.google.common.base.MoreObjects;

/**
 * TipoDeCultivo generated by hbm2java
 */
@Entity
@Table(name="tipo_de_cultivo"
    ,catalog="jpro"
)
public class TipoDeCultivo  implements java.io.Serializable {


     private int idTipoDeCultivo;
     private String nombreDePlanta;
     private String claseDePlanta;
     private String descipcion;
   
     @Id 

    
    @Column(name="id_tipo_de_cultivo", unique=true, nullable=false)
    public int getIdTipoDeCultivo() {
        return this.idTipoDeCultivo;
    }
    
    public void setIdTipoDeCultivo(int idTipoDeCultivo) {
        this.idTipoDeCultivo = idTipoDeCultivo;
    }

    
    @Column(name="Nombre_de_planta", length=45)
    public String getNombreDePlanta() {
        return this.nombreDePlanta;
    }
    
    public void setNombreDePlanta(String nombreDePlanta) {
        this.nombreDePlanta = nombreDePlanta;
    }

    
    @Column(name="Clase_de_planta", length=45)
    public String getClaseDePlanta() {
        return this.claseDePlanta;
    }
    
    public void setClaseDePlanta(String claseDePlanta) {
        this.claseDePlanta = claseDePlanta;
    }

    
    @Column(name="Descipcion", length=200)
    public String getDescipcion() {
        return this.descipcion;
    }
    
    public void setDescipcion(String descipcion) {
        this.descipcion = descipcion;
    }

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("idTipoDeCultivo", idTipoDeCultivo)
				.add("nombreDePlanta", nombreDePlanta).add("claseDePlanta", claseDePlanta).add("descipcion", descipcion)
				.toString();
	}


    

}


