package com.jorge.springmvc.model;
// Generated 18/03/2016 11:50:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import com.google.common.base.MoreObjects;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name="tipo_usuario"
    ,catalog="jpro"
)
public class TipoUsuario  implements java.io.Serializable {


     private int idTipoUsuario;
     private String tipo;
     private String descripcion;
   
     @Id 

    
    @Column(name="id_tipo_usuario", unique=true, nullable=false)
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this).add("idTipoUsuario", idTipoUsuario).add("tipo", tipo)
				.add("descripcion", descripcion).toString();
	}


    

}


