package com.jorge.springmvc.model;
// Generated 21/07/2017 05:30:53 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idUsuario;
	private int idRole;

	public UserId() {
	}

	public UserId(int idUsuario, int idRole) {
		this.idUsuario = idUsuario;
		this.idRole = idRole;
	}

	@Column(name = "ID_USUARIO", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_ROLE", nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario()) && (this.getIdRole() == castOther.getIdRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdRole();
		return result;
	}

}
