package com.jorge.springmvc.model;
// Generated 21/07/2017 05:30:53 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "jito_db")
public class User implements java.io.Serializable {

	private UserId id;
	private Role role;
	private int perfil;
	private String username;
	private String name;
	private String lastName;
	private String password;
	private String email;
	private Set harvests = new HashSet(0);
	private Set logs = new HashSet(0);

	public User() {
	}

	public User(UserId id, Role role, int perfil, String username, String name, String lastName, String password,
			String email) {
		this.id = id;
		this.role = role;
		this.perfil = perfil;
		this.username = username;
		this.name = name;
		this.lastName = lastName;
		this.password = password;
		this.email = email;
	}

	public User(UserId id, Role role, int perfil, String username, String name, String lastName, String password,
			String email, Set harvests, Set logs) {
		this.id = id;
		this.role = role;
		this.perfil = perfil;
		this.username = username;
		this.name = name;
		this.lastName = lastName;
		this.password = password;
		this.email = email;
		this.harvests = harvests;
		this.logs = logs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "ID_USUARIO", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "ID_ROLE", nullable = false)) })
	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ROLE", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "PERFIL", nullable = false)
	public int getPerfil() {
		return this.perfil;
	}

	public void setPerfil(int perfil) {
		this.perfil = perfil;
	}

	@Column(name = "USERNAME", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "NAME", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getHarvests() {
		return this.harvests;
	}

	public void setHarvests(Set harvests) {
		this.harvests = harvests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getLogs() {
		return this.logs;
	}

	public void setLogs(Set logs) {
		this.logs = logs;
	}

}
